### ISSUE TITLE
"Btrfs and dirvish, a perfect match"

### ISSUE THREAD

**Issue by mgrunwald** [knorrie/btrfs-heatmap#10]
Sorry to use this way to contact you, but I found no other way to contact you. I'm very interested in the patch that you mentioned here

https://www.mendix.com/blog/btrfs-dirvish-perfect-match/

Unfortunately, there is no trace of that patch. Is it still available somewhere?

**Comment by knorrie** [comment]
Hi! Here's a copy: https://paste.debian.net/plainh/1beb46ac
It's some perl duct taping that I'm not proud of, but it does the job.

**Comment by mgrunwald** [comment]
Hey, thanks a lot! I'm about to patch debians dirvish-package and now I can include your improvements of the original post. Of course, I'll mention you and the original author.

Bonus kudos if you could tell me how you " convert[ed] all old snapshots into new btrfs snapshots, while still making sure daily backups could run in a consistent way every night." 0:)

**Comment by knorrie** [comment]
That was done early 2015, at the same time we moved from the ext4 based filesystem for backup storage to btrfs. When moving existing backup snapshots to the new btrfs filesystem, it was simply done by creating the first subvolume, rsyncing the data, snapshotting it, rsyncing the next one from ext4, etc, essentially doing the same as the regular nightlies would do, but then fast forwarding it.

It was not done in-place, so I don't have ready-made tooling for that lying around. However, for a one-off action like that, a decent sysadmin should be able to write something quickly. Just only putting the most recent data into a subvolume would suffice (cp with reflink once), but then you need to detect if tree is a btrfs subvol or not while expiring the older ones.

**Comment by berlincount** [comment]
> Hi! Here's a copy: https://paste.debian.net/plainh/1beb46ac
> It's some perl duct taping that I'm not proud of, but it does the job.

sadly, that paste expired :-/

**Comment by mgrunwald** [comment]
> sadly, that paste expired :-/

In case you use debian: I filed a wishlist bugreport to dirvish in Debian, but the maintainer seems to be in hibernation mode:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944488

There's a debdiff in the bugreport, so you should be able to create a debian package with btrfs support. Use `alien` to convert it to whatever you need. PM me if you need help.

BTW: that patch has been running for over a year now and it works perfectly :)

**Comment by mgrunwald** [comment]
> sadly, that paste expired :-/

In case you use debian: I filed a wishlist bugreport to dirvish in Debian, but the maintainer seems to be in hibernation mode:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944488

There's a debdiff in the bugreport, so you should be able to create a debian package with btrfs support. Use `alien` to convert it to whatever you need. PM me if you need help.

BTW: that patch has been running for over a year now and it works perfectly :)

**Comment by berlincount** [comment]
@mgrunwald nice, thank you! I'll give it a try ...

anything I need to know / convert / change when upgrading an existing `dirvish-bank` to this way of doing it?

I figure expire won't work the same? 🤔

**Comment by mgrunwald** [comment]
I feel a bit bad that I captured this issue... Please contact me via berlincount.thegrue@spamgourmet.com if you need further communication or if I should send you the dpkg.

My way of "conversion" ended up like this:
- Remove the harddisk with the old backup, store it safely
- Add a new (bigger, because bigger is better ;) ) harddisk
- Format that with btrfs
- Add the "btrfs" keyword to the configuration (see man dirvish.conf)
- Initialise the vaults

knorrie mentioned a way to convert old backups, but for my use case it was overkill.
It's sad, that the debian maintainer kind of stopped working on that package :( I might start poking upstream.
