### ISSUE TITLE
Man page missing from regular releases

### ISSUE THREAD

**Issue by evils** [knorrie/btrfs-heatmap#11]
Please add the man page to the master branch so it gets included in generic/non-debian releases.
Related to https://github.com/NixOS/nixpkgs/pull/86861

**Comment by knorrie** [comment]
Hi evils,

Yes, this will happen. Or, it actually already has happened, if you look at the develop branch.

I'm finishing up the python-btrfs v12 release now, and then I will also do a new btrfs-heatmap release.

Hans
