### ISSUE TITLE
BTRFS mounted on BTRFS shows the top most filesystem

### ISSUE THREAD

**Issue by dewitpj** [knorrie/btrfs-heatmap#5]
Hi,

I have 2 BTRFS filesystems, one mount on /srv and one mounted on /srv/temp.

Running:

btrfs-heatmap -o srv.png /srv
and
btrfs-heatmap -o srv_temp.png /srv/temp

Creates the same image ?

**Comment by knorrie** [comment]
Hi, thanks for trying btrfs-heatmap!

Are you sure that it's not the same filesystem? Can you share the output of `grep btrfs /proc/self/mounts`?

**Comment by dewitpj** [comment]
Hi,

Sorry for the delay:

/dev/sdb1 /srv btrfs rw,relatime,space_cache,autodefrag,subvolid=5,subvol=/ 0 0
/dev/sdc1 /srv/temp btrfs rw,relatime,space_cache,subvolid=5,subvol=/ 0 0

**Comment by knorrie** [comment]
And some more debugging? What does `btrfs fi show` say?

And if you do this in a python3 session?
```
>>> import btrfs
>>> btrfs.FileSystem('/srv').fsid
UUID('b9c720e3-c839-4e0b-b708-563d7b424290')  <- will show some different uuid for you
>>> btrfs.FileSystem('/srv/temp').fsid
UUID('7cc60652-cb82-4c13-81c0-6ca221e4e62e') <- and this should show a different one again
```

I'd really expect these two uuids to be different.

And, if you run those exact btrfs-heatmap commands with the option `-v`, and without the `-o` option, does it generate two pictures with the same filesystem uuid in the name?

**Comment by dewitpj** [comment]
wow - ok - very sorry about this....seems something got crossed over somewhere - turns out that I was using /srv/temp and I should have used /srv/some_other_name

Again, very sorry :(

**Comment by knorrie** [comment]
Ok, no problem, good to hear you figured it out. :) Have fun creating pictures.
